### ISSUE TITLE
Querying for contact links

### ISSUE THREAD

**Issue by SabreBirdOne** [RafaelCenzano/LabConnect#27]
Users likely want contact information from specific lab runners as part of their search for opportunities

**To do list**
Get contact links based on table attribute: contact_type 
Get contact links that specific lab runners have (given their rcs_ids)
Get contact links with a specific substring. Example: ".com", ".us", "@gmail.com", etc.

**Comments**
This is a small issue. If you plan on resolving many smaller issues in a single branch, please coordinate carefully with the rest of the team.

**Comment by RafaelCenzano** [comment]
No longer an issue as database models have been updated to a different method
